[profile.default]
src = 'src'
out = 'out'
libs = ['lib', "dependencies"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

## (duplicated profile removed)

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
